import type { ExecuteJobResult, ValidationResult } from "../../../runtime/offeringTypes.js";

export async function executeJob(request: any): Promise<ExecuteJobResult> {
  const {
    topic,
    contentType = "blog",
    tone = "professional",
    maxLength = "500",
  } = request.requirements || {};

  const templates: Record<string, string> = {
    tweet: `🌙 LUNA here with insights on ${topic}!\n\nKey points:\n• This is a rapidly evolving space worth watching\n• Early movers have significant advantages\n• The data speaks for itself\n\nStay tuned for more. #${topic?.replace(/\s+/g, "")} #ACP #VirtualsProtocol`,

    thread: `🧵 Thread: Everything you need to know about ${topic}\n\n1/ The landscape is changing fast. Here's why ${topic} matters now more than ever.\n\n2/ The fundamentals are solid. Data shows consistent growth and adoption.\n\n3/ Key opportunities: early adoption, strategic positioning, and network effects.\n\n4/ Risks to consider: market volatility, regulatory shifts, and competition.\n\n5/ Bottom line: ${topic} represents a significant opportunity for those paying attention.\n\nFollow @LUNA for more insights. 🌙`,

    blog: `# ${topic}: A Comprehensive Overview\n\n## Introduction\n\n${topic} has emerged as one of the most significant developments in recent times. This article explores the key aspects, implications, and opportunities that this presents.\n\n## Why It Matters\n\nThe impact of ${topic} cannot be understated. As we navigate an increasingly complex landscape, understanding the nuances of this topic becomes critical for decision-makers and enthusiasts alike.\n\n## Key Insights\n\n- **Growth trajectory**: The space has seen remarkable expansion\n- **Adoption patterns**: Early adopters are gaining significant advantages  \n- **Future outlook**: Analysts remain optimistic about long-term potential\n\n## Conclusion\n\n${topic} represents a pivotal opportunity. Whether you're a seasoned professional or just starting out, staying informed is your greatest asset.\n\n*Generated by LUNA — Autonomous AI Agent on Virtuals Protocol*`,

    marketing: `🚀 Introducing: ${topic}\n\nWhy settle for ordinary when you can have extraordinary?\n\n✅ Proven results\n✅ Cutting-edge approach  \n✅ Built for scale\n\nJoin the thousands already benefiting from ${topic}. The future is here — don't get left behind.\n\n📩 Learn more today.`,

    summary: `**Summary: ${topic}**\n\n${topic} is a key concept that encompasses several important dimensions. At its core, it represents a shift in how we approach problem-solving and value creation.\n\n**Key Takeaways:**\n1. The fundamental principles are straightforward yet powerful\n2. Real-world applications are broad and growing\n3. The opportunity window remains open for early movers\n\n*Concise analysis by LUNA Agent*`,

    "product-description": `**${topic}**\n\nDiscover the power of ${topic} — designed for those who demand excellence.\n\nFeatures:\n• Industry-leading performance\n• Intuitive and easy to use\n• Built to last\n\nWhether you're a professional or enthusiast, ${topic} delivers exactly what you need, when you need it.\n\n*Premium quality. Exceptional value.*`,
  };

  const content = templates[contentType] || templates["blog"];

  return {
    deliverable: content,
  };
}

export function validateRequirements(request: any): ValidationResult {
  const { topic, contentType } = request.requirements || {};
  if (!topic) return { valid: false, reason: "Missing required field: topic" };
  const validTypes = ["blog", "tweet", "thread", "marketing", "summary", "product-description"];
  if (contentType && !validTypes.includes(contentType)) {
    return {
      valid: false,
      reason: `Invalid contentType. Must be one of: ${validTypes.join(", ")}`,
    };
  }
  return { valid: true };
}

export function requestPayment(request: any): string {
  const { topic, contentType = "blog" } = request.requirements || {};
  return `LUNA will generate ${contentType} content about "${topic}". Payment of 0.1 USDC confirms the job.`;
}
